CREATE DATABASE task_fetcher;
USE task_fetcher;

CREATE TABLE users(
  uid INTEGER(11) NOT NULL AUTO_INCREMENT,
  usrname VARCHAR(50) NOT NULL,
  pwd VARCHAR(100) NOT NULL,
  slt VARCHAR(20) NOT NULL,
  PRIMARY KEY(uid)
);

CREATE TABLE tasks(
  tid INTEGER(11) NOT NULL AUTO_INCREMENT,
  uid INTEGER(11) NOT NULL,
  title VARCHAR(100) NOT NULL,
  description VARCHAR(100) NOT NULL,
  done TINYINT(1) DEFAULT 0 NOT NULL,
  PRIMARY KEY(tid),
  FOREIGN KEY(uid) REFERENCES users(uid)
);

